### ISSUE TITLE
Unable to search by description

### ISSUE THREAD

**Issue by julienGrd** [ICD-API/csharp-samples#12]
Hello, in the officiel website (https://icd.who.int/browse/2024-01/mms/fr) we are able to search by Description. (in advanced search)

With the API, It seem we can also specify where to search but im unable to search by Description

This is the properties we can use actually in propertiesToBeSearched : Title,FullySpecifiedName,Definition,Exclusion,IndexTerm,RelatedImpairment,CodingNote

put all this elements in the search seem not looking into the description

Can you confirm is not supported for the moment ? if yes is it something which is planned ?

thanks !

**Comment by mdonada** [comment]
Hi,

The `propertiesToBeSearched=Definition` is the correct parameter to use.
The Description (in the Browser's advanced search) is the Definition property in the API.

Please note, you can search using the `propertiesToBeSearched` only when `medicalCodingMode=false`.

For example, you need to set both `medicalCodingMode=false` and `propertiesToBeSearched=Definition` 

These info are also in the API-Reference (swagger) https://id.who.int/swagger/index.html

**Comment by julienGrd** [comment]
ok thanks, i was looking at the wrong service in swagger (one which not contains the medicalCodingMode parameter)

With your explanation everything works now
