### ISSUE TITLE
When enter search word, it give me error

### ISSUE THREAD

**Issue by MrMustafa-2** [ICD-API/csharp-samples#2]
Hello, when the program ask me for search word, for example "blood"  , it give me that error:
Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: R. Path '', line 0, position 0.'

**Comment by cannn** [comment]
Thanks for letting us know. 
The code was assuming that the beta version is served in the API. The issue is corrected now.

**Comment by MrMustafa-2** [comment]
It is good, thank you Cannn, but I have another issue, as when I search with "Blood" for example, It give me only the **Destination Entities**, and I also want the **Word list**
Can you help me please coz I am working on project now for using the web service
