### ISSUE TITLE
How to get the Word list in search result

### ISSUE THREAD

**Issue by MrMustafa-2** [ICD-API/csharp-samples#3]
I have another issue, as when I search with "Blood" for example, It give me only the **Destination Entities**, but I also want the **Word list** to be get in the search result
Also I want to search with code for example: code for specific **Destination Entities** like **MA12.0**
I use this URL but it not give me the details of specific **Destination Entities**
https://id.who.int/icd/release/11/2021-05/mms/codeinfo/MA12.0
Can you help me please coz I am working on project now for using the web service

**Comment by cannn** [comment]
You could get the wordlist by adding includeKeywordResult=true in the
search call. Please see the our open API (swagger)
<https://id.who.int/swagger/index.html>docs for all endpoints and
parameters,

In our API, the main identifiers are the URIs, codeinfo provides the URI of
the entity in the stemId field. Once you receive the response from
codeinfo, make another call to the URI that is returned in the stemId, this
would give you all the information on the entity. This contains more
information than the destinationentity which is used in the response to
search request.

best,

can

**Comment by MrMustafa-2** [comment]
Thanks Can, it is work, but it not give the result I want, I want for example when I search for "blood", it give me result like in that image, the required search result I mark it with red rectangle in this image:
https://ibb.co/jbTd7Yg

**Comment by MrMustafa-2** [comment]
Any body here ...

**Comment by mdonada** [comment]
Hi,

You have to add the wildcard character % at the end of your search text (the "q" param).

Searching "blood" returns this word list:
-vessels
-injury
-level
-other
-abnormal
...

Searching "blood%" returns this word list:
-blood
-blood-alcohol
-blood-brain
-blood-clot
-blood-drug
...

For any doubt, please refer to our swagger page: https://id.who.int/swagger/index.html 

Best,
Marc

**Comment by MrMustafa-2** [comment]
Thanks Can, last question please,
If I want to get only words without destination Entities, How can I get only Words ?
